//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pRatio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("conf\\QuiXML.xsd")]
        public string quiXML_Schema {
            get {
                return ((string)(this["quiXML_Schema"]));
            }
            set {
                this["quiXML_Schema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("conf\\aminoacids_weight.xsd")]
        public string aaWeight_Schema {
            get {
                return ((string)(this["aaWeight_Schema"]));
            }
            set {
                this["aaWeight_Schema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("conf\\aminoacids_weight.xml")]
        public string aaWeight_XML {
            get {
                return ((string)(this["aaWeight_XML"]));
            }
            set {
                this["aaWeight_XML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.007825")]
        public float HydrogenMass {
            get {
                return ((float)(this["HydrogenMass"]));
            }
            set {
                this["HydrogenMass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15.994915")]
        public float OxygenMass {
            get {
                return ((float)(this["OxygenMass"]));
            }
            set {
                this["OxygenMass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("conf\\pepXML_v18.xsd")]
        public string pepXML_Schema {
            get {
                return ((string)(this["pepXML_Schema"]));
            }
            set {
                this["pepXML_Schema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5.5.00")]
        public string version {
            get {
                return ((string)(this["version"]));
            }
            set {
                this["version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("conf\\bioW33.xsd")]
        public string bioW33_Schema {
            get {
                return ((string)(this["bioW33_Schema"]));
            }
            set {
                this["bioW33_Schema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("conf\\modifications.xsd")]
        public string modifications_Schema {
            get {
                return ((string)(this["modifications_Schema"]));
            }
            set {
                this["modifications_Schema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.007276466812")]
        public double ProtonMass {
            get {
                return ((double)(this["ProtonMass"]));
            }
            set {
                this["ProtonMass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13.0033548378")]
        public double C13Mass {
            get {
                return ((double)(this["C13Mass"]));
            }
            set {
                this["C13Mass"] = value;
            }
        }
    }
}
